
export enum SOCKET_EVENT {
    USER_CONNECTED = "USER_CONNECTED",
    USER_DISCONNECTED= "USER_DISCONNECTED",
    ROOM_CREATED="ROOM_CREATED",
    NEW_MESSAGE = "NEW_MESSAGE",
    VIDEO_QUEUED = "VIDEO_QUEUED",
    VIDEO_ENDED = "VIDEO_ENDED",
    SKIP_VIDEO="SKIP_VIDEO"
} 

