export enum SOCKET_EVENT {
    CONNECT="connect",
    USER_CONNECT = "USER_CONNECT",
    USER_DISCONNECTED= "USER_DISCONNECTED",
    SET_QUEUE_ON_CONNECT="SET_QUEUE_ON_CONNECT",
    ROOM_CREATED="ROOM_CREATED",
    NEW_MESSAGE = "NEW_MESSAGE",
    VIDEO_QUEUED = "VIDEO_QUEUED",
    VIDEO_ENDED = "VIDEO_ENDED",
    SKIP_VIDEO="SKIP_VIDEO",
    VOTE_TO_SKIP="VOTE_TO_SKIP",
    SKIPPING_IN_PROGRESS="SKIPPING_IN_PROGRESS",
    JOIN_ROOM="JOIN_ROOM",
  } 
  